### ISSUE TITLE
text layerの文字数が0のときに起動すると、入力した文字が反映されない

### ISSUE THREAD

**Issue by mtakada16** [ryonakae/figma-plugin-edit-text#1]
一度Edit Textを閉じて、text layerに1文字以上テキストを入力し、再びEdit Textを起動すると反映されるようになります。

- - -

![output](https://user-images.githubusercontent.com/9247205/85418500-ceb19100-b5ab-11ea-9f3d-7c34824426b7.gif)

- - - 

## 期待する挙動
- text layerを新規作成 -> Text Editを起動 -> 入力 の手順で正常に文字列がtext layer側に反映される

## 動作環境
- Figma Desktop App release 86 (Build 4)
- macOS Catalina Version 10.15.6 Beta
- Google 日本語入力

**Comment by ryonakae** [comment]
@kiepng 遅くなりましたが、とても丁寧なissueを書いていただき、ありがとうございました！
（GIFまで貼ってくださってありがとうございます🙇‍♂️）
#7 にて、プラグインの挙動を以下のように修正しました。

### テキストレイヤーの文字数が0文字のときの挙動
* 1文字以上あるテキストレイヤーをEditTextプラグインで編集し、文字を消して0文字にした状態でプラグインを閉じた場合、テキストレイヤーに半角スペースを1つ挿入する
  - 0文字のテキストレイヤーを選択した状態でプラグインを起動→文字入力をしても、文字が反映されません
  - 半角スペースが1つでも入っているテキストレイヤーであれば、EditTextで編集可能
  - 原因は現在調査中ですが、それが解決するまでは、いったんこの対応とさせてください🙇‍♂️

### プラグイン起動時の挙動
* テキストレイヤーは選択しているがテキスト編集中ではない場合（ただレイヤーをシングルクリックして選択している状態。キャレットが表示されていない状態）のときにプラグインを起動すると、textareaのテキストを全選択した状態にする
  - ↑の半角スペースが1つだけ挿入されてしまう問題を多少緩和できる挙動
  - テキストレイヤーの文字数を0にしてプラグインを閉じる→テキストレイヤーには半角スペースが1つだけある→プラグインを起動するとその半角スペースが選択されている→Backspaceを押さずに、テキストを入力するだけで半角スペースを消すことができる
  - 単純に、プラグインを起動したときにテキスト編集中じゃないなら全選択しといて欲しいなぁと思っただけ、というのもあります

ちなみにその他は、以下のような修正をしています。

* テキストを編集中（レイヤーをダブルクリックでキャレットを表示している状態）で、キャレットを文字の最後にした場合に、プラグインのtextareaでキャレットの位置が反映されない問題を修正

そのうちマージしてFigmaにPublishしますので、お待ち下さい！
