### ISSUE TITLE
入力中にカーソルが末尾に移動してしまうことがある

### ISSUE THREAD

**Issue by mtakada16** [ryonakae/figma-plugin-edit-text#2]
正確な発生条件がわかっていないのですが、入力中にカーソル位置が末尾に移動してしまうことがあるようです。
体感では

- 文章が複数行ある状態で
  - 一定以上の速度で入力しているとき
  - 変換キーを押したとき

に発生することが多いようです。
- - - 
![output](https://user-images.githubusercontent.com/9247205/85419592-403e0f00-b5ad-11ea-9329-0fdb4f297730.gif)

- - - 

## 期待する挙動
入力中の文字列が正常に入力されること

## 動作環境
- Figma Desktop App release 86 (Build 4)
- macOS Catalina Version 10.15.6 Beta
- Google 日本語入力

**Comment by ryonakae** [comment]
@kiepng 大変遅くなり申し訳ありませんが、丁寧なissueを書いていただいてどうもありがとうございます！
分かりやすいGIFや動作環境についても感謝です！

僕の方でも検証してみましたが、イマイチ再現性がない不具合でした😭
肌感なんですが、あまりスペックの高くないPCでFigmaを開いてこのプラグインを使っていると、比較的発生しやすいのかな？と感じました。

これも予想なんですが（どれも曖昧ですみません）、PCのスペックによっては、リアルタイムでプラグインのテキストをFigmaのテキストレイヤーに反映する処理が追いつかず、プラグインから一時的にフォーカスが外れ、入力中のテキストが確定してしまう（キャレットが末尾に移動してしまう）んじゃないかな？と考えています🤔

これに対する解決策、とは厳密には違いますが、 #5 でテキストリアルタイム編集のオン・オフを切り替えられるようにしました。
そこまでスペックが高くないPCではリアルタイム編集をオフにしていただくと、不具合なく入力いただけるかも知れません。

そのうちマージしてFigmaにPublishしますので、お待ち下さい！
どうもありがとうございました！
